---
title: "My typological database"
output:
  html_document:
    theme: paper
    include:
      after_body: footer.html
    toc: true
    toc_depth: 5
    toc_float: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, echo=FALSE}
library(DT)
library(tidyverse)
library(lingtypology)
library(knitr)
```


This site presents **the X Database**, a typological database of X in the world's languages.

---

### Sample

The database contains information on X in 10 languages.

```{r, include=FALSE, echo=FALSE}
df <- read.csv("sample.csv")
```


```{r, echo=FALSE}
map.feature(languages = df$language,
            features = df$family,
            label = df$language,
            popup = df$family
            )

```



---

### Structure of the database

My description.





---

### Data

The table below shows the collected information on each of the continuative expressions in the database. To see more columns, click on the `Column visibility` button.

```{r echo = FALSE, results = 'asis', message=FALSE, warning=FALSE}
library(readr)
library(DT)
datatable(
  data = df,
  filter = "top",
  extensions = 'Buttons', options = list(dom = 'Bfrtip', columnDefs = list(list(visible=FALSE, targets=c(0,1,2,3,4,5,7,9,10,11,12,13,14,16,18,20,22,23))),
  buttons = list(list(extend = 'colvis', columns = c(1,2,3,4,5,7,9,10,11,12,13,14,16,18,20,22,23))))
)
```


